package com.group5final.roomieradar.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity class representing a household in the RoomieRadar application.
 * <p>
 * A household is a group of users sharing chores, events, and other resources.
 * This class is mapped to the "household" table in the database and uses JPA annotations for persistence.
 * </p>
 */
@Getter
@Setter
@Entity
@Table(name = "household", schema = "roomieRadarData")
public class Household {

    /**
     * Unique identifier for the household, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    /**
     * The name of the household, which must be unique and non-null.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * The password for accessing or joining the household, stored as plain text (consider hashing for security).
     */
    @Column(name = "password", nullable = false)
    private String password;
}